# Generated by Django 3.2.16 on 2023-04-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sulg',
            new_name='slug',
        ),
    ]
