# Generated by Django 3.2.16 on 2023-05-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_sulg_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draf', 'Draft'), ('publisehd', 'Publisehd')], default='draft', max_length=10),
        ),
    ]
