# Generated by Django 3.2.16 on 2023-05-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draf', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
