# Generated by Django 3.2.16 on 2023-05-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewcount',
            name='ip_address',
            field=models.CharField(max_length=250),
        ),
    ]
